package agentproxy

const (
	CodeDirectDNS                  = "direct_dns"
	CodeDirectConnect              = "direct_connect"
	CodeDirectTLS                  = "direct_tls"
	CodeDirectRoundTrip            = "direct_round_trip"
	CodeDirectCircuitOpen          = "direct_circuit_open"
	CodeDirectCircuitHalfOpen      = "direct_circuit_half_open"
	CodeDirectCircuitCapacity      = "direct_circuit_capacity"
	CodeDirectInvalidInput         = "direct_invalid_input"
	CodeDirectBody                 = "direct_body"
	CodeDirectResponseCopy         = "direct_response_copy"
	CodeDirectClosed               = "direct_closed"
	CodeDirectDisabled             = "direct_disabled"
	CodeDirectIngressUnsupported   = "direct_ingress_unsupported"
	CodeDirectAuthUnavailable      = "direct_auth_unavailable"
	CodeDirectIdentityMismatch     = "direct_identity_mismatch"
	CodeDirectProbeInvalidResponse = "direct_probe_invalid_response"
	CodeDirectCommitUncertain      = "direct_commit_uncertain"
	CodeDirectResponseInterrupted  = "direct_response_interrupted"
	CodeRelayNotReady              = "relay_not_ready"
	CodeRelayCommitUncertain       = "relay_commit_uncertain"
	CodeRelayResponseInterrupted   = "relay_response_interrupted"
	CodeRequestCancelled           = "request_cancelled"
	CodeRequestDeadline            = "request_deadline"
)
