package consts

// RPC/WebSocket 方法名常量。
const (
	RPCSyncFullSync            = "sync.fullSync"
	RPCSyncGetVersion          = "sync.getVersion"
	RPCSyncPush                = "sync.push"
	RPCSyncRequestFullSync     = "sync.requestFullSync"
	RPCSyncForceFullSync       = "sync.forceFullSync"
	RPCSyncAutoAddrUpdate      = "sync.autoAddrUpdate"
	RPCSyncFetchEntity         = "sync.fetchEntity"
	RPCSyncUserQuota           = "sync.userQuota"
	RPCSyncAgentCapabilities   = "sync.agentCapabilities"
	RPCAgentAuthBootstrap      = "agent.authBootstrap"
	RPCAgentIssueRelayTicket   = "agent.issueRelayTicket"
	RPCAgentIssueForwardTicket = "agent.issueForwardTicket"
	RPCAgentHeartbeat          = "agent.heartbeat"
	RPCAgentOperation          = "agent.operation"
	RPCAgentCheckConnectivity  = "agent.checkConnectivity"
	RPCAgentDirectProbe        = "agent.directProbe"
	RPCAgentRelayProbe         = "agent.relayProbe"
	RPCAgentInflight           = "agent.inflight"
	RPCAgentGoroutines         = "agent.goroutines"
	RPCAgentInterrupt          = "agent.interrupt"
	RPCAgentLimiterUsage       = "agent.limiterUsage"
	RPCAgentBreakers           = "agent.breakers"
	RPCAgentUsageQueue         = "agent.usageQueue"
	RPCAgentUsageQueueOp       = "agent.usageQueueOp"
	RPCAgentRouteTelemetry     = "agent.routeTelemetry"
	RPCAgentRouteDigest        = "agent.routeDigest"
	RPCChannelTest             = "channel.test"
	RPCChannelFetchModels      = "channel.fetchModels"
	RPCReportUsage             = "report.usage"
)
